# Generated by Django 6.0.4 on 2026-04-24 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_group_grouptopic_groupmessage_groupmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEncryptedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphertext', models.TextField()),
                ('iv', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributed_keys', to=settings.AUTH_USER_MODEL)),
                ('encrypted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_keys', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_keys', to='chats.group')),
            ],
            options={
                'unique_together': {('group', 'encrypted_for')},
            },
        ),
    ]
